### PR TITLE
Fixed Bugs

### PR DESCRIPTION
**Pull request by HemangMishra1234**
1. Fixed the navigation bug.
2. Fixed the app crash issue due to package name issue.
3. Fixed another bug while saving the profile picture.
4. Added the Reference screenshots so that the developers can refer it during the development process.

#52 Fixes the navigatio issues

## Changes
Added popBackStack at relevant locations.

https://github.com/sourabhkumar47/ResQFood/assets/132752204/f60e7866-cc31-4e47-b424-417f999f877f

### CODE REVIEW

**Comment by sourabhkumar47** [comment]
Great!

**Comment by Lucky-chelani** [comment]
Just a suggestion can we change app theme to blue red or something else

**Comment by HemangMishra1234** [comment]
In that case, we might have to change the logo as well. Because I had just extracted the theme from the logo itself. Please do share your ideas.

**Comment by sourabhkumar47** [comment]
> In that case, we might have to change the logo as well. Because I had just extracted the theme from the logo itself. Please do share your ideas.

The current logo is good, primary focus is on the app will see this later on.

**Pull request merged**
