### PR TITLE
Feature added to collect personal information after sign in

### PR DESCRIPTION
**Pull request by HemangMishra1234**
#30 
Collecting Name, email, phone number and gender.
Amount of data collected is less in order to reduce friction.
These details are stored in firestore.
If users log in through google account, profile photo is automatically collected.
Users can upload their profile photos as well which will be stored in firebase storage.
WhatsApp Image 2024-05-18 at 09 30 43_3bdc8fb4

### CODE REVIEW

**Comment by sourabhkumar47** [comment]
Need some modifications 
- Bring profile icon more close to TextFields  
- For Gender use drop down menu 
- Add field for Address

**Comment by HemangMishra1234** [comment]
Okay. I'll get it done

**Comment by HemangMishra1234** [comment]
WhatsApp Image 2024-05-18 at 15 30 43_c784ce1a

@sourabhkumar47 Done

**Comment by sourabhkumar47** [comment]
Looks Wonderfull!

**Pull request merged**
